server:
  port: 8769

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  routes:
    # routes 是一个 Map<String, ZuulRoute> 类型对象，
    # 所以api-a是key，其下配置是 ZuulRoute 对象对应的属性
    api-a:
      path: /api-a/**
      serviceId: ribbon
    # routes 中的另一个键值对
    api-b:
      path: /api-b/**
      serviceId: feign
